version: "3.7"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1430:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword!

  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: library/rabbitmq:3.8-management
    ports:
      - 5670:5672
      - 15670:15672
    volumes:
      - ./docker-support/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
