spring:
  application:
    name: configuration-service

  datasource:
    url: jdbc:sqlserver://localhost:1430;databaseName=rfantasy;applicationName=config
    username: sa
    password: P@ssword!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    pool-name: HikariPool-RFANTASY-config
    initialization-mode: never
    continue-on-error: false

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: config
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        proc.param_null_passing: true

  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAIL_TRAP_USERNAME_CRED}
    password: ${MAIL_TRAP_PASSWORD_CRED}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
server:
  error:
    include-message: always
  port: 8081
